[package]
name = "chipr-8"
version = "0.1.0"
authors = ["Guilherme Prado <grprado.bsb@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
sdl2 = "0.33.0"